name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo6 cmake libffi-dev libssl-dev
          pip install buildozer cython

      - name: Install Android SDK
        run: |
          sudo apt install -y wget
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          mkdir -p $HOME/android-sdk/cmdline-tools
          unzip commandlinetools-linux-9477386_latest.zip -d $HOME/android-sdk/cmdline-tools
          export PATH=$PATH:$HOME/android-sdk/cmdline-tools/tools/bin
          yes | sdkmanager --licenses
          sdkmanager "build-tools;30.0.3"

      - name: Build APK
        run: |
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4.3.0
        with:
          name: apk
          path: bin/*.apk
